type Rashi = {
  id: number;
  name_english: string;
  name_hindi: string;
  ruling_planet: string;
  color_hindi: string;
  color_english: string;
  sign: string;
  symbol: string;
  phonetic: string;
  gemstone_hindi: string;
};

const rashiList: Rashi[] = [
  {
    id: 1,
    name_english: 'Aries',
    name_hindi: 'मेष',
    ruling_planet: 'Mangal',
    color_hindi: 'सिन्दूरी',
    color_english: 'Red',
    sign: 'Mesh',
    symbol: '♈',
    phonetic: 'Mēḍhā',
    gemstone_hindi: 'मूंगा',
  },
  {
    id: 2,
    name_english: 'Taurus',
    name_hindi: 'वृषभ',
    ruling_planet: 'Shukra',
    color_hindi: 'सफेद',
    color_english: 'White',
    sign: 'Vrushabh',
    symbol: '♉',
    phonetic: 'Bēla',
    gemstone_hindi: 'हीरा',
  },
  {
    id: 3,
    name_english: 'Gemini',
    name_hindi: 'मिथुन',
    ruling_planet: 'Budh',
    color_hindi: 'हरा',
    color_english: 'Green',
    sign: 'Mithun',
    symbol: '♊',
    phonetic: 'Yuvā Dam̐patti',
    gemstone_hindi: 'पन्ना',
  },
  {
    id: 4,
    name_english: 'Cancer',
    name_hindi: 'कर्क',
    ruling_planet: 'Chandra',
    color_hindi: 'सफेद',
    color_english: 'White',
    sign: 'Kark',
    symbol: '♋',
    phonetic: 'Kaiḳaḍā',
    gemstone_hindi: 'मोती',
  },
  {
    id: 5,
    name_english: 'Leo',
    name_hindi: 'सिंह',
    ruling_planet: 'Surya',
    color_hindi: 'लाल',
    color_english: 'Gold',
    sign: 'Sinh',
    symbol: '♌',
    phonetic: 'Māṇikya',
    gemstone_hindi: 'माणिक्य',
  },
  {
    id: 6,
    name_english: 'Virgo',
    name_hindi: 'कन्या',
    ruling_planet: 'Budh',
    color_hindi: 'हरा',
    color_english: 'Green',
    sign: 'Kanya',
    symbol: '♍',
    phonetic: 'Kumārī Kanyā',
    gemstone_hindi: 'पन्ना',
  },
  {
    id: 7,
    name_english: 'Libra',
    name_hindi: 'तुला',
    ruling_planet: 'Shukra',
    color_hindi: 'सफेद',
    color_english: 'White',
    sign: 'Tula',
    symbol: '♎',
    phonetic: 'Tarājū',
    gemstone_hindi: 'हीरा',
  },
  {
    id: 8,
    name_english: 'Scorpius',
    name_hindi: 'वृश्चिक',
    ruling_planet: 'Mars',
    color_hindi: 'सिन्दूरी',
    color_english: 'Red',
    sign: '',
    symbol: '♏',
    phonetic: 'Vrushchik',
    gemstone_hindi: 'मूंगा',
  },
  {
    id: 9,
    name_english: 'Sagittarius',
    name_hindi: 'धनु',
    ruling_planet: 'Jupiter',
    color_hindi: 'पीला',
    color_english: 'Yellow',
    sign: '',
    symbol: '♐',
    phonetic: 'Dhanu',
    gemstone_hindi: 'पुखराज',
  },
  {
    id: 10,
    name_english: 'Capricornus',
    name_hindi: 'मकर',
    ruling_planet: 'Saturn',
    color_hindi: 'नीला',
    color_english: 'Blue',
    sign: '',
    symbol: '♑',
    phonetic: 'Makar',
    gemstone_hindi: 'नीलम',
  },
  {
    id: 11,
    name_english: 'Aquarius',
    name_hindi: 'कुंभ',
    ruling_planet: 'Saturn',
    color_hindi: 'नीला',
    color_english: 'Blue',
    sign: '',
    symbol: '♒',
    phonetic: 'Kumbha',
    gemstone_hindi: 'नीलम',
  },
  {
    id: 12,
    name_english: 'Pisces',
    name_hindi: 'मीन',
    ruling_planet: 'Jupiter',
    color_hindi: 'पीला',
    color_english: 'Yellow',
    sign: '',
    symbol: '♓',
    phonetic: 'Meen',
    gemstone_hindi: 'पुखराज',
  },
];
